version: '3.8'
services:
  app:
    build: .
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: admin-db
      MYSQL_PASSWORD: P@$t@db1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  mysql_data: